version: '3.9'

services:
  user-postgres:
    image: postgres:15-alpine
    container_name: user-postgres
    ports:
      - '${POSTGRES_PORT}:5432'
    env_file:
      - '../.env'
    volumes:
      - user_service_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped


volumes:
  user_service_postgres_data: