version: '3.9'

services:
#  tests-user-redis:
#    image: redis:latest
#    container_name: tests-user-redis
#    ports:
#      - '${TESTS_REDIS_PORT}:6379'
#    volumes:
#      - tests_user_service_redis_data:/data
#    env_file:
#      - ../.env.tests
  tests-user-postgres:
    image: postgres:15-alpine
    container_name: tests-user-postgres
    ports:
      - '${TESTS_POSTGRES_PORT}:5432'
    env_file:
      - ../.env.tests
    volumes:
      - tests_user_service_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${TESTS_POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
#  tests_user_service_redis_data:
  tests_user_service_postgres_data:
