version: '3.9'

services:
  user_service:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: user_service
    ports:
      - '${USER_SERVICE_API_PORT}:8000'
    command: 'uvicorn --factory application.api.main:create_app --reload --host 0.0.0.0 --port 8000'
    env_file:
      - ../.env
    volumes:
      - ../src/:/src/
